#Python image with slim variant for smaller size
FROM python:3.12-slim
# Set working directory inside the container
WORKDIR /app

#Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

#Copy requirements file to the container
COPY requirements.txt .

#Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

#Copy backend code
COPY app ./app

#Run FastAPI server using Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
